profile_security:
    path: /security
    controller: App\Controller\ProfileController::securityAction

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/security"

profile_driver_token:
    path: /driver-token
    controller: App\Controller\ProfileController::driverTokenAction

profile_generate_tfa:
    path: /security/generate-tfa
    controller: App\Controller\ProfileController::generateTfaAction

